service: shopify-csv-generator

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage}
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:ListAllMyBuckets
            - s3:PutObject
            - s3:GetObject
            - s3:CreateBucket
            - s3:PutLifecycleConfiguration
          Resource: "arn:aws:s3:::*"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*" 
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:CreateTable
            - dynamodb:ListTables
            - dynamodb:DescribeTable
            - dynamodb:UpdateTimeToLive
          Resource: "arn:aws:dynamodb:sa-east-1:421852645480:table/*"
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:DescribeParameters
          Resource: "*"
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueUrl
          Resource: 
            - "arn:aws:sqs:sa-east-1:*:shop-processor-queue-${self:provider.stage}"
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            Fn::Join:
              - ":"
              - - "arn:aws:sns"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - 
                  Fn::Join:
                    - "-"
                    - - "LambdaErrorNotifications"
                      - ${self:provider.stage}
        - Effect: Allow
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

package:
  exclude:
    - .env
    - DEPRECATED/**

functions:
  triggerProcessing:
    handler: handler.trigger_shop_processing
    timeout: 30
    logRetentionInDays: 5
    environment:
      STAGE: ${self:provider.stage}
      SQS_QUEUE_NAME: shop-processor-queue-${self:provider.stage}
    events:
      ${self:custom.weeklyCronEvent.${self:provider.stage}}

  processShop:
    handler: handler.process_shop
    timeout: 30
    logRetentionInDays: 5
    environment:
      STAGE: ${self:provider.stage}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ShopProcessorQueue
              - Arn
          batchSize: 1  # Procesa un mensaje (tienda) a la vez.

resources:
  Resources:
    ShopProcessorQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: shop-processor-queue-${self:provider.stage}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    requirementsFile: requirements.txt
  weeklyCronEvent:
    prod:
      - schedule: cron(0 18 * * ? *)
    dev: []
