service: shopify-csv-generator

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
        - s3:HeadBucket
        - s3:CreateBucket
      Resource: "arn:aws:s3:::*"

functions:
  csv-generator:
    handler: handler.lambda_handler
    events:
      - http:
          path: csv-generator
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    requirementsFile: requirements.txt
